### ISSUE TITLE
add support for /dev/rfcommX for linux

### ISSUE THREAD

**Issue by wandiufo** [nathandunk/BetterSerialPlotter#10]
Dear Developer
I am interested in using BetterSerialPlotter under Linux.
I am using serial over Bluetooth (HC06) to communicate with hardware Arduino Uno. 
Under windows, the Bluetooth binding to COMX has the same name format as other serial ports and successfully detects and works by BetterSerialPlotter. 
But under linux the bluetooth binding to /dev/rfcommX and can not detect by BetterSErialPlotter (may be because different name format /dev/ttyUSBX).
Could you help me with how to make BetterSerialPlotter can detect the /dev/rfcommX?
Thank you very much for your help.
Best regards,
Irwandi

**Comment by nathandunk** [comment]
Hi @wandiufo , I think I can fix this without too much trouble. Give me a bit of time and I think I can add this functionality.

**Comment by nathandunk** [comment]
Hi @wandiufo. Can you try out this version and let me know if it works? I don't have the ability to test on my machine, but I think it should do the trick. If it works, I'll add a release.
[BetterSerialPlotter.zip](https://github.com/nathandunk/BetterSerialPlotter/files/9592412/BetterSerialPlotter.zip)

**Comment by nathandunk** [comment]
Support for several more port types have been added in [this release](https://github.com/nathandunk/BetterSerialPlotter/releases/tag/v0.1.2).
