### ISSUE TITLE
Is this intended for Win10 and up ???

### ISSUE THREAD

**Issue by softfoot** [nathandunk/BetterSerialPlotter#14]
I ask this because I see an error when run under WIN7 about a missing dll.
See attached.
Dave

![SerialPlotError](https://user-images.githubusercontent.com/9020648/209882205-8f7f1d48-7bc8-4dfb-bf14-8cff344910d3.jpg)

**Comment by nathandunk** [comment]
Yes, it is only supported on Windows 10+ at the moment. I don't have any Windows 7 machines to compile on, but I think if I did have one, it would be feasible. At this point, I don't know if there is enough interest to support this at the moment.
