### ISSUE TITLE
IM_ASSERT "PushID/PopID or TreeNode/TreePop Mismatch!" with x64, Windows MSVC

### ISSUE THREAD

**Issue by maleiter** [nathandunk/BetterSerialPlotter#6]
Hi, 

I'm trying to build the BetterSerialPlotter on Windows using Visual Studio 22. 
When executing, the IM_ASSERT "PushID/PopID or TreeNode/TreePop Mismatch!" fails. 
A comment states, that this assertion is intended to detect usage errors of ImGui. 

Is it possible, that there is actually a usage error of ImGui/mahi-gui?

Thanks!

**Comment by maleiter** [comment]
I've fixed it in PR https://github.com/nathandunk/BetterSerialPlotter/pull/7

**Comment by nathandunk** [comment]
This is fixed in [this commit](https://github.com/nathandunk/BetterSerialPlotter/commit/8298c59870d732247c0d80d32ae93e5d44ddc0ea).
